apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-source-cluster-2
spec:
  kafka:
    # version: 2.7.0
    replicas: 2
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      offsets.topic.replication.factor: 2
      transaction.state.log.replication.factor: 2
      transaction.state.log.min.isr: 1
    storage:
      type: ephemeral
    resources:
      requests:
        memory: 512Mi
        cpu: 300m
      limits:
        memory: 1024Mi
        cpu: 500m
    template:
      pod:
        tolerations:
        - key: ""
          operator: "Exists"
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml
  zookeeper:
    replicas: 2
    storage:
      type: ephemeral
    resources:
      requests:
        memory: 256Mi
        cpu: 250m
      limits:
        memory: 512Mi
        cpu: 400m
    template:
      pod:
        tolerations:
        - key: ""
          operator: "Exists"
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: zookeeper-metrics
          key: zookeeper-metrics-config.yml
  kafkaExporter:
    groupRegex: ".*"
    topicRegex: ".*" 
    resources:
      requests:
        cpu: 600m
        memory: 128Mi
      limits:
        cpu: 700m
        memory: 256Mi
    template:
      pod:
        tolerations:
        - key: ""
          operator: "Exists"
  cruiseControl:
    resources:
      requests:
        cpu: 400m
        memory: 400Mi
      limits:
        cpu: 600m
        memory: 512Mi
    template:
      pod:
        tolerations:
        - key: ""
          operator: "Exists"
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: cruise-control-metrics
          key: metrics-config.yml
  entityOperator:
    topicOperator:
      resources:
        requests:
          memory: 256Mi
          cpu: 200m
        limits:
          memory: 512Mi
          cpu: 300m
    userOperator:
      resources:
        requests:
          memory: 256Mi
          cpu: 200m
        limits:
          memory: 512Mi
          cpu: 300m
