apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{.Release.Namespace}}-prometheus-server
  labels:
    app: strimzi
  namespace: {{include "amq-streams.namespace" .}}
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/proxy
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Release.Namespace}}-prometheus-server
  labels:
    app: strimzi

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{.Release.Namespace}}-prometheus-server
  labels:
    app: strimzi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{.Release.Namespace}}-prometheus-server
subjects:
  - kind: ServiceAccount
    name: {{.Release.Namespace}}-prometheus-server
    namespace: {{.Release.Namespace}}

---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: {{.Release.Namespace}}-prometheus
  labels:
    app: strimzi
spec:
  replicas: {{ .Values.monitoring.prometheus.replicas}}
  serviceAccountName: prometheus-server
  podMonitorSelector:
    matchLabels:
      app: strimzi
  serviceMonitorSelector: {}
  resources:
    requests:
      memory: {{ .Values.monitoring.prometheus.memory}}
  enableAdminAPI: false
  ruleSelector:
    matchLabels:
      role: alert-rules
      app: strimzi
  alerting:
    alertmanagers:
      - namespace: {{ .Release.Namespace }}
        name: alertmanager
        port: alertmanager
  additionalScrapeConfigs:
    name: additional-scrape-configs
    key: prometheus-additional.yaml
