apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    role: alert-rules
    app: strimzi
  name: {{.Release.Name}}-prometheus-k8s-rules
  namespace: {{include "amq-streams.namespace" .}}
spec:
  {{- toYaml .Values.kafkaPrometheusRules | nindent 2 }}
